' Generated by zxp2boriel.py
' Source: spriteset.zxp
' Size: 16x16
' Count: 1

Dim sprite0(31) As Ubyte => { _
	$00,$00,$00,$07,$3F,$7F,$BF,$9F, _
	$8F,$8F,$9F,$FF,$3F,$1F,$07,$00, _
	$00,$00,$00,$C0,$A0,$10,$28,$28, _
	$88,$FC,$82,$7C,$88,$F8,$80,$00 _
}

